### ISSUE TITLE
Allowed characters in display names setting applies.  link issue

### ISSUE THREAD

**Issue by Deltafox79** [Recouse/IPS-Instagram-Login-Handler#2]
Into settings application instagram you have a link : 

> **Allowed characters in display names** setting applies. 

 to point to : 

...app=core&module=membersettings&controller=profiles&tab=**settings**&searchResult=username_characters

but tab **settings** is not present to fix this change to **profilesettings** int his way : 

app=core&module=membersettings&controller=profiles&tab=**profilesettings**&searchResult=username_characters

![immagine](https://user-images.githubusercontent.com/2518850/41587303-3032e23a-73af-11e8-8c85-12b3a1ec72d3.jpg)

Regards

**Comment by Recouse** [comment]
Have you tested this on other login handlers?

**Comment by Deltafox79** [comment]
Ues probably is Ipb link issue.. the problems is present also in other login handle.. tk's and regards

**Comment by Deltafox79** [comment]
ok can be fixed on language ipb translation search key **login_real_name_desc**

change

`<a href='{internal.app=core&module=membersettings&controller=profiles&tab=settings&searchResult=username_characters}' target='_blank'>Allowed characters in display names</a> setting applies. `

to

> <a href='{internal.app=core&module=membersettings&controller=profiles&tab=profilesettings&searchResult=username_characters}' target='_blank'>Allowed characters in display names</a> setting applies. 

Regards

**Comment by Recouse** [comment]
OK. I'm closing the issue.
